[style]: Blog設定基本CSS樣式和首頁排版更新
astrocamp/14th-READMee pull request #19
Opened 2023-08-15 16:47 UTC by thekuen

首頁排版
1.導覽列放上logo
![image](https://github.com/astrocamp/14th-READMee/assets/138368310/46534a95-b9fd-4f24-8175-634e7b1a440a)

Blog CRUD建立設定CSS樣式
![image](https://github.com/astrocamp/14th-READMee/assets/138368310/a5bbe7da-5c19-45e3-a872-a94d59adedd6)

2023-08-15 23:17 UTC, DOJO004 commented on app/controllers/blogs_controller.rb
> +    @blog = Blog.find(params[:id])
可以整理成 before action

2023-08-15 23:18 UTC, DOJO004 commented on app/views/blogs/edit.html.erb
> +<div class="my-4 flex gap-3">
縮排要調整一下

2023-08-16 07:33 UTC, thekuen commented on app/views/blogs/edit.html.erb
> +<div class="my-4 flex gap-3">
8/16縮排已更新

2023-08-16 11:38 UTC, viiining requested changes

2023-08-16 11:38 UTC, viiining commented on app/models/blog.rb
第 4, 5, 6 行 可以移除空行

2023-08-16 13:15 UTC, DOJO004 commented on app/views/blogs/new.html.erb
> +	<%= f.label :title, '標題' %>
縮排要整理一下

2023-08-17 02:29 UTC, cacachang requested changes

2023-08-17 02:29 UTC, cacachang commented on .gitignore
> +.rubocop.yml
這把它拿出來

2023-08-17 02:29 UTC, cacachang commented on .gitignore
> +.env
應該不會用到 .env 檔案吧？ 你們是用 master key

2023-08-17 02:29 UTC, cacachang commented on app/helpers/blogs_helper.rb
> +module BlogsHelper
沒用到就刪掉吧

2023-08-18 06:22 UTC, viiining commented on app/assets/stylesheets/application.tailwind.css
> +
第 12 行以下都移除

2023-08-18 08:08 UTC, DOJO004 approved these changes

2023-08-18 10:35 UTC, komaki009 submitted a review, later dismissed

2023-08-18 11:32 UTC, cacachang requested changes

2023-08-18 11:32 UTC, cacachang commented on app/views/layouts/application.html.erb
> +      </head>
縮

2023-08-19 07:37 UTC, q2379685 commented on app/controllers/blogs_controller.rb
> +
多於空行

2023-08-19 07:38 UTC, q2379685 commented on app/helpers/profiles_helper.rb
> +module ProfilesHelper
這個是不是可以刪掉

2023-08-19 07:40 UTC, q2379685 commented on app/javascript/controllers/previews_controller.js
> +    const reader = new FileReader();
想問這行的new是在做甚麼

2023-08-19 07:42 UTC, q2379685 commented on app/views/blogs/index.html.erb
> +                                turbo_confirm: '確定要刪除?'
是不是少空兩行

2023-08-19 08:03 UTC, komaki009 approved these changes

2023-08-19 08:09 UTC, viiining commented on app/controllers/blogs_controller.rb
> +    find_blog
多寫？

2023-08-19 08:09 UTC, viiining commented on app/controllers/blogs_controller.rb
> +    find_blog
多寫？

2023-08-19 08:09 UTC, viiining commented on app/controllers/blogs_controller.rb
> +    find_blog
同上

2023-08-19 08:09 UTC, viiining commented on app/controllers/blogs_controller.rb
> +    find_blog
同上

2023-08-19 08:09 UTC, viiining commented on app/javascript/controllers/previews_controller.js
> +    const reader = new FileReader();
FileReader() 是一個 Web APIs，可以讀取儲存在用戶端的檔案

2023-08-20 03:46 UTC, komaki009 approved these changes

2023-08-20 05:13 UTC, DOJO004 commented on .vscode/settings.json
這個檔案不要進檔控

2023-08-20 15:46 UTC, komaki009 approved these changes

2023-08-21 03:46 UTC, DOJO004 submitted a review, later dismissed

2023-08-21 03:49 UTC, viiining approved these changes

2023-08-21 04:37 UTC, komaki009 approved these changes

2023-08-21 04:37 UTC, DOJO004 approved these changes

2023-08-21 04:41 UTC, viiining approved these changes

2023-08-21 04:43 UTC, q2379685 approved these changes

2023-08-21 04:44 UTC, merged

2023-08-22 09:04 UTC, cacachang commented on app/views/devise/registrations/_new.html.erb
>    <%= form_for(resource, as: resource_name, url: registration_path(resource_name)) do |f| %>
縮排

2023-08-22 09:04 UTC, cacachang commented on app/views/layouts/application.html.erb
> +  <nav class="relative max-w-7xl w-full mx-auto px-4 sm:flex sm:items-center sm:justify-between sm:px-6 lg:px-8" aria-label="Global">
這可以包成一個 html 檔案，在用 render 方式帶進來