[feat]: Resume editor
astrocamp/14th-READMee pull request #21
Opened 2023-08-16 08:47 UTC by dawn-huang621

可以修改儲存履歷的基本資料，社群連結，個人簡介，工作經驗的區塊
在上面的文字區塊點擊後會變成填寫的textarea
點擊儲存更新，畫面不會跳轉，但資料已經成功存入了

https://github.com/astrocamp/14th-READMee/assets/82479899/216f424b-fa68-407c-9643-4f15fe7953ab

2023-08-16 13:33 UTC, DOJO004 submitted a review, later dismissed

2023-08-18 04:11 UTC, komaki009 submitted a review, later dismissed

2023-08-18 04:22 UTC, thekuen approved these changes

2023-08-18 04:22 UTC, thekuen commented on .gitignore
35行好像多一行空白

2023-08-18 04:22 UTC, thekuen commented on app/controllers/resumes_controller.rb
> +  include ActionView::Helpers::SanitizeHelper
請問SanitizeHelper是您這邊做的嗎，主要的功能是?

2023-08-18 04:22 UTC, thekuen commented on app/javascript/controllers/resume_controller.js
請問幫忙說明stateFocus 的意思?

2023-08-18 05:46 UTC, viiining requested changes

2023-08-18 05:46 UTC, viiining commented on app/views/resumes/edit.html.erb
> +      <a href="https://flowbite.com/" class="flex items-center">
這連結為何要連去 flowbite?

2023-08-18 05:46 UTC, viiining commented on app/views/resumes/edit.html.erb
> +        <span class="self-center text-2xl font-semibold whitespace-nowrap dark:text-white">Flowbite</span>
這應該要改成 READMee

2023-08-18 05:46 UTC, viiining commented on app/assets/images/skill.png
除了 R logo 這些圖片檔是不是不需要放了

2023-08-18 06:00 UTC, q2379685 commented on app/javascript/controllers/resume_controller.js
加註解嗎?stateFocus如果已經有表單，就不要再做一次顯示隱藏

2023-08-18 06:16 UTC, q2379685 commented on app/controllers/resumes_controller.rb
> +  include ActionView::Helpers::SanitizeHelper
是 Ruby on Rails 中的一個模組，用於幫助處理和清理 HTML 和文本內容，以防止潛在的跨站腳本攻擊（XSS 攻擊）。這個模組提供了一些方法，可以將文本內容中的特殊字符和標籤進行過濾或轉義

2023-08-18 06:22 UTC, q2379685 commented on app/views/resumes/edit.html.erb
> +      <a href="https://flowbite.com/" class="flex items-center">
我有刪了

2023-08-18 07:23 UTC, komaki009 approved these changes

2023-08-18 07:43 UTC, viiining approved these changes

2023-08-18 08:07 UTC, DOJO004 submitted a review, later dismissed

2023-08-18 10:18 UTC, DOJO004 approved these changes

2023-08-18 10:18 UTC, viiining approved these changes

2023-08-18 10:20 UTC, komaki009 approved these changes

2023-08-18 10:28 UTC, thekuen submitted a review, later dismissed

2023-08-18 10:34 UTC, thekuen submitted a review, later dismissed

2023-08-18 10:35 UTC, thekuen approved these changes

2023-08-19 08:37 UTC, thekuen submitted a review, later dismissed

2023-08-20 15:45 UTC, komaki009 approved these changes

2023-08-21 08:07 UTC, komaki009 submitted a review, later dismissed

2023-08-21 08:21 UTC, DOJO004 approved these changes

2023-08-21 08:30 UTC, DOJO004 approved these changes

2023-08-21 08:34 UTC, komaki009 approved these changes

2023-08-21 09:09 UTC, viiining approved these changes

2023-08-21 09:11 UTC, DOJO004 approved these changes

2023-08-21 09:30 UTC, viiining approved these changes

2023-08-21 09:31 UTC, DOJO004 approved these changes

2023-08-21 09:31 UTC, komaki009 approved these changes

2023-08-21 09:31 UTC, thekuen approved these changes

2023-08-21 09:32 UTC, merged