[build]: Job
astrocamp/14th-READMee pull request #4
Opened 2023-08-08 14:37 UTC by komaki009

第一版的職缺crud與切版

2023-08-08 23:40 UTC, DOJO004 approved these changes

2023-08-11 06:35 UTC, q2379685 approved these changes

2023-08-15 12:24 UTC, cacachang requested changes

2023-08-15 12:24 UTC, cacachang commented on package-lock.json
> +  "name": "14th-READMee",
沒有用 npm 或 yarn 的話就不用這個

2023-08-15 12:24 UTC, cacachang commented on package.json
> +  "dependencies": {
同上

2023-08-15 12:24 UTC, cacachang commented on test/fixtures/jobs.yml
> +
沒寫測試可以刪除

2023-08-16 08:16 UTC, komaki009 commented on app/views/jobs/_form.html.erb
> +        <%= f.text_field :company_name, class: "w-full" %>
這行沒有了

2023-08-16 14:15 UTC, cacachang commented
有衝突

2023-08-18 03:13 UTC, closed without merging