[style]: 增加pricing頁面以及排版
astrocamp/14th-READMee pull request #49
Opened 2023-08-26 16:40 UTC by komaki009

增加了pricing頁面以及排版
![螢幕擷取畫面 2023-08-26 230441](https://github.com/astrocamp/14th-READMee/assets/140598406/f9229b67-d646-4dba-ab65-703b35d19e60)

2023-08-26 21:33 UTC, DOJO004 commented on app/views/prices/show.html.erb
> +              移除 CakeResume 品牌
是不是打錯字
這裡應該不是要寫 CakeResume吧

2023-08-26 21:39 UTC, DOJO004 commented on app/views/prices/show.html.erb
> +    <!-- End Switch -->
這一長串註解是什麼?

2023-08-26 21:41 UTC, DOJO004 commented on app/views/prices/show.html.erb
> +      <samp class="mt-1">可隨時取消7 天內退款保證</samp>
"7" 天 可以前後都有空格 看起來比較順眼

2023-08-26 21:41 UTC, DOJO004 commented on app/views/prices/show.html.erb
> +  </dev>
是不是少一個 /dev標籤 檢查一下

2023-08-27 01:38 UTC, viiining requested changes

2023-08-27 02:38 UTC, DOJO004 commented on app/views/prices/show.html.erb
> +  </dev>
欸對 我打錯 拍謝

2023-08-27 04:06 UTC, viiining commented on app/views/prices/show.html.erb
> +  <!-- Pricing -->
這種註解也可以移除

2023-08-27 13:21 UTC, komaki009 commented on app/views/prices/show.html.erb
> +              移除 CakeResume 品牌
改了

2023-08-27 13:21 UTC, komaki009 commented on app/views/prices/show.html.erb
> +      <samp class="mt-1">可隨時取消7 天內退款保證</samp>
OK

2023-08-27 13:22 UTC, komaki009 commented on app/views/prices/show.html.erb
> +  </dev>
修正了

2023-08-27 13:22 UTC, komaki009 commented on app/views/prices/show.html.erb
> +  <!-- Pricing -->
都拿掉了

2023-08-28 04:12 UTC, viiining approved these changes

2023-08-28 04:14 UTC, DOJO004 approved these changes

2023-08-28 04:15 UTC, q2379685 approved these changes

2023-08-28 04:15 UTC, thekuen approved these changes

2023-08-28 04:16 UTC, merged