[build]: 建立 profile CRUD
astrocamp/14th-READMee pull request #9
Opened 2023-08-14 08:35 UTC by viiining

- profile 首頁面
<img width="1043" alt="profile:show" src="https://github.com/astrocamp/14th-READMee/assets/130339657/3964d39b-0a48-4e3d-a487-eb8786e59187">

- profile 建立與編輯頁面
<img width="1117" alt="profile:new" src="https://github.com/astrocamp/14th-READMee/assets/130339657/7a8a826e-61f9-42ef-b724-ee5fbb0b02da">
<img width="1135" alt="profile:edit" src="https://github.com/astrocamp/14th-READMee/assets/130339657/4fc6f890-0098-4428-8e25-423be636694a">

2023-08-14 08:39 UTC, komaki009 approved these changes

2023-08-14 08:40 UTC, DOJO004 submitted a review, later dismissed

2023-08-14 08:43 UTC, q2379685 submitted a review, later dismissed
ok

2023-08-15 12:32 UTC, komaki009 submitted a review, later dismissed

2023-08-15 16:46 UTC, cacachang requested changes

2023-08-15 16:46 UTC, cacachang commented on config/routes.rb
> +  resource :profile, except: [:destroy]
跑 rubocop 修改縮排

2023-08-15 16:46 UTC, cacachang commented on app/controllers/profiles_controller.rb
> +    @profile = current_user
devise 應該有給 current_user 的方法，不用另外寫

2023-08-15 16:46 UTC, cacachang commented on app/helpers/profiles_helper.rb
> +end
沒用到就刪掉吧

2023-08-15 16:46 UTC, cacachang commented on app/models/profile.rb
> +  def add_language(language, level)
這個什麼時候會用到

2023-08-15 16:46 UTC, cacachang commented on app/views/profiles/_form.html.erb
> +        <% ["English", "Spanish", "French", "German", "Chinese", "Japanese"].each do |language| %>
這可以放到 helper 也試試 options_for_select

2023-08-15 16:46 UTC, cacachang commented on app/views/profiles/show.html.erb
> +        <%#= image_tag(@profile.avatar, class: "rounded-full w-32 h-32 mx-auto") if @profile.avatar.present? %>
做完整再放上來，不要有這種註解出現

2023-08-15 16:46 UTC, cacachang commented on app/views/profiles/show.html.erb
> +            <!-- 第一版履歷區塊 -->
同上

2023-08-15 16:46 UTC, cacachang commented on test/models/profile_test.rb
> +
沒要寫測試就刪

2023-08-15 16:46 UTC, cacachang commented on test/fixtures/profiles.yml
> +# Read about fixtures at https://api.rubyonrails.org/classes/ActiveRecord/FixtureSet.html
同上

2023-08-15 16:46 UTC, cacachang commented on test/controllers/profiles_controller_test.rb
> +
同上

2023-08-15 16:46 UTC, cacachang commented on app/models/profile.rb
> +  validates :full_name, :phone, :address, :education, :about_me, :work_experience, presence: true
`full_name` `phone` `address` 是必填，可是畫面沒有

2023-08-15 16:46 UTC, cacachang commented on app/controllers/profiles_controller.rb
> +    @profile = Profile.new(profile_params)
這應該會錯吧？ user_id 沒寫進去

2023-08-16 13:23 UTC, DOJO004 commented on app/views/profiles/_avatar_preview.html.erb
> +	<div class="m-5">
縮排要調整一下

2023-08-16 13:25 UTC, DOJO004 commented on app/views/profiles/edit.html.erb
> +    <% end %>
縮排調整一下

2023-08-16 14:34 UTC, cacachang requested changes

2023-08-16 14:34 UTC, cacachang commented on .gitignore
> +.rubocop.yml
為什麼這個要放在 gitignore

2023-08-16 14:34 UTC, cacachang commented on app/controllers/profiles_controller.rb
> +    @profile.skills.build
這應該沒有存起來

2023-08-16 14:34 UTC, cacachang commented on app/views/profiles/show.html.erb
> +              <%#= 之後要改成 link_to 訂閱路徑 %>
抓

2023-08-16 14:54 UTC, viiining commented on config/routes.rb
> +  resource :profile, except: [:destroy]
有的，已更新～！
<img width="817" alt="Screenshot 2023-08-16 at 10 54 20 PM" src="https://github.com/astrocamp/14th-READMee/assets/130339657/204a3fb5-0910-4f03-b1ea-0ae9b5675161">

2023-08-16 14:57 UTC, cacachang commented on app/controllers/profiles_controller.rb
> +    @profile.skills.build
抱歉，看到你用的是 `nested_attribute`，所以這寫法是對的

2023-08-16 14:58 UTC, kaochenlong commented on .vscode/settings.json
> +      "username": "chih-ningchang"
這個檔案應該在 gitignore 裡，而且怎麼資料庫的連線設定是寫在這裡？

2023-08-16 14:58 UTC, kaochenlong commented on Gemfile
> +gem "rubocop", "~> 0.90.0"
這種東西放在 `development` 裡，另外應該使用 `rubocop-rails`

2023-08-16 14:58 UTC, kaochenlong commented on app/javascript/controllers/nested_form_controller.js
> +    super.connect();
這個檔案等於沒做任何事

2023-08-18 04:13 UTC, q2379685 approved these changes

2023-08-18 04:13 UTC, q2379685 commented on app/views/profiles/show.html.erb
> +      </section>
縮排有問題

2023-08-18 04:21 UTC, DOJO004 approved these changes

2023-08-18 04:24 UTC, thekuen approved these changes

2023-08-18 05:37 UTC, viiining commented on .vscode/settings.json
這已經有先移除，不會有影響

2023-08-18 05:37 UTC, viiining commented on app/assets/stylesheets/application.tailwind.css
右邊是目前最新的檔案，已移除註解了唷！

2023-08-18 05:37 UTC, viiining commented on app/views/profiles/show.html.erb
> +      </section>
已更新

2023-08-18 05:37 UTC, viiining commented on db/migrate/20230810090758_create_active_storage_tables.active_storage.rb
是的

2023-08-18 05:47 UTC, komaki009 approved these changes

2023-08-18 05:48 UTC, merged